### PR TITLE
run some single node jobs on AWS

### PR DESCRIPTION
**Pull request by goneri**
The goal of this job is to validate we can run single node jobs on AWS.

### CODE REVIEW

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by pabelanger** [comment]
> The goal of this job is to validate we can run single node jobs on AWS.

I don't mind we we add nodes into aws, but we cannot limit jobs just to aws.  This would be a step backwards for jobs to be run only in a single region. And, we won't be able to gate jobs with that, for fear of an outage will block zuul from merging code.

**Comment by goneri** [comment]
Superseded by https://github.com/ansible-network/windmill-config/pull/696

**Pull request closed without merging**
