### PR TITLE
Upgrade eos from 4.20 to 4.24

### PR DESCRIPTION
**Pull request by GomathiselviS**
Signed-off-by: GomathiselviS <gosriniv@redhat.com>

### CODE REVIEW

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Review by sc68cal — APPROVED** [review]

**Comment by GomathiselviS** [comment]
recheck

**Comment by sc68cal** [comment]
There are numerous tests that fail against newer versions of EOS due to the syntax changes. I don't think we would be able to merge the update to the newer EOS version without making the job non-voting on PR's.

**Comment by GomathiselviS** [comment]
> There are numerous tests that fail against newer versions of EOS due to the syntax changes. I don't think we would be able to merge the update to the newer EOS version without making the job non-voting on PR's.

Hi @sc68cal I am working on upgrading the software. I will start working on the cli changes once the infra is ready. I am hoping to get them all merged ( your PRs inclusive) before the release which will happen by the end of this month. If not, we shall release eos, with all the fixes needed for the cli syntax changes, early next month ( August 2021).

**Comment by GomathiselviS** [comment]
> Again, I am saying that updating the CI to run `4.26` of Arista EOS will cause many of the tests in the https://github.com/ansible-collections/arista.eos/ repository to fail. Meaning all merges will be blocked in that repo. The tests have to be updated before we merge the change to CI, or we need to change the CI jobs to be non-voting to allow merges to continue while we make the fixes to the CLI syntax

@sc68cal yes, that is the plan of action. This PR will be merged, only after the tests are updated. Until then the CI infra will have the older eos software.

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Pull request merged**
