### PR TITLE
ensure we properly test the ansible-test-* roles

### PR DESCRIPTION
**Pull request by goneri**

### CODE REVIEW

**Comment by goneri** [comment]
@pabelanger I would like to merge this to avoid any new ansible-test breakage in the future.

**Comment by pabelanger** [comment]
Seems fine, can you just touch the role now, to validate the jobs actually pass?

**Comment by goneri** [comment]
They all pass fine currently:

- https://dashboard.zuul.ansible.com/t/ansible/builds?job_name=ansible-test-network-integration-openvswitch-python35
- https://dashboard.zuul.ansible.com/t/ansible/builds?job_name=ansible-test-cloud-integration-vcenter7_only-python36
- https://dashboard.zuul.ansible.com/t/ansible/builds?job_name=ansible-test-units-openvswitch-python38

**Comment by pabelanger** [comment]
No, I was saying, can they be run from ansible-zuul-jobs. Sometimes the jobs are not setup to be cloned or run on another project.

Mostly thinking of vmware and ovs units.

**Comment by goneri** [comment]
ah!

Let's check that :-D

**Comment by goneri** [comment]
> No, I was saying, can they be run from ansible-zuul-jobs. Sometimes the jobs are not setup to be cloned or run on another project.
> 
> Mostly thinking of vmware and ovs units.

and this was indeed a good idea :-).

**Pull request merged**
