### PR TITLE
Add ios stable-2.12 integration test jobs

### PR DESCRIPTION
**Pull request by Qalthos**

### CODE REVIEW

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Review by GomathiselviS — CHANGES_REQUESTED** [review]
Please add `ansible-test-sanity-docker-stable-2.12 ` for ios  . Refer [vyos](https://github.com/ansible/ansible-zuul-jobs/pull/1144/files#diff-d6a059f0e5ce0b0099801f8f1b6817ae2d0822e13f833c60f072558bee0117daR770)

**Comment by Qalthos** [comment]
I didn't catch that those were split by platform, thanks

**Comment by Qalthos** [comment]
recheck

**Pull request merged**
