### PR TITLE
community.vmware: Remove sanity and unity tests

### PR DESCRIPTION
**Pull request by mariolenz**
Depends-On: https://github.com/ansible-collections/community.vmware/pull/1747

Remove sanity and unity tests from community.vmware.

ansible-collections/community.vmware#1746

### CODE REVIEW

**Comment by mariolenz** [comment]
recheck

**Comment by mariolenz** [comment]
recheck

**Comment by mariolenz** [comment]
@alinabuzachis @GomathiselviS @gravesm I don't understand the error I'm running into here. Do you think it can have something to do with #1797?

**Review by jillr — DISMISSED** [review]
lgtm

**Comment by mariolenz** [comment]
@jillr Any idea why this fails? As far as I can see, my changes didn't touch anything about amazon.cloud at all :shrug:

**Comment by gravesm** [comment]
@mariolenz I think this is cause by the amazon.cloud project being removed from https://github.com/ansible/zuul-config. Double checking but I think we may just need to remove the jobs that reference the amazon.cloud project from here.

**Comment by GomathiselviS** [comment]
[This PR](https://github.com/ansible/ansible-zuul-jobs/pull/1804) should fix the issue.

**Comment by GomathiselviS** [comment]
recheck

**Review by jillr — APPROVED** [review]

**Comment by mariolenz** [comment]
Thanks @GomathiselviS @gravesm @jillr!

**Pull request merged**
