### PR TITLE
Pull request for rename_netconf_jobs

### PR DESCRIPTION
**Pull request by danielmellado**
## Add junos cli jobs

This commit adds junos cli transport jobs.

## Rename junos netconf jobs

This PR renames netconf junos jobs, as well as junos netcommon
integration jobs.

Signed-off-by: Daniel Mellado <dmellado@redhat.com>

### CODE REVIEW

**Comment by danielmellado** [comment]
Pull-request updated, HEAD is now f866abc8c36f7ffa2b2a4ddd906a21ae167c2e8b

**Comment by danielmellado** [comment]
recheck

**Comment by goneri** [comment]
The run in https://github.com/ansible-collections/junipernetworks.junos/pull/45 has failed. Do you know why?

**Comment by danielmellado** [comment]
Probably because this being dependant on another patch?
I'm a gerrit guy originally so not really sure, let's ask Paul on it.

**Comment by danielmellado** [comment]
recheck

**Comment by pabelanger** [comment]
no longer needed

**Pull request closed without merging**
