### PR TITLE
Remove servicenow.itsm tests

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
- Bugfix Pull Request

### CODE REVIEW

**Comment by Akasurde** [comment]
cc @Gomathiselvi-S

**Review by jillr — APPROVED** [review]

**Comment by jillr** [comment]
recheck

**Comment by jillr** [comment]
recheck

**Comment by Akasurde** [comment]
@jillr Thanks for the review and merge.

**Pull request merged**
