### PR TITLE
WIP: Update fedora-latest to fedora-32

### PR DESCRIPTION
**Pull request by pabelanger**
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/589
Signed-off-by: Paul Belanger <pabelanger@redhat.com>

### CODE REVIEW

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
marking this WIP, as not sure what the cost is to update fedora-latest.  I'll look to see which jobs us it by default

**Comment by goneri** [comment]
closing, fedora-32 is enabled.

**Pull request closed without merging**
